### ISSUE TITLE
Not cut comments from animate.css

### ISSUE THREAD

**Issue by faitno** [sindresorhus/gulp-strip-css-comments#1]
Not cut comments from animate.css:
https://github.com/daneden/animate.css/blob/master/animate.css
out .css file have this:

```
/*!
 * animate.css -http://daneden.me/animate
 * Version - 3.5.0
 * Licensed under the MIT license - http://opensource.org/licenses/MIT
 *
 * Copyright (c) 2016 Daniel Eden
 */
```

**Comment by sindresorhus** [comment]
The answer is right there in the docs: https://github.com/sindresorhus/gulp-strip-css-comments#options

**Comment by faitno** [comment]
but I set in options

```
{preserve: false}
```

and only in animate.css it not cut comments. In all other css files it work all right.
