### ISSUE TITLE
Doesn't work with node v4.2.1

### ISSUE THREAD

**Issue by DarthVanger** [sindresorhus/gulp-strip-css-comments#3]
`gulp-strip-css-comments` version: 2.0.0
`gulp` version: 3.9.1
Node version:
```
npm info using npm@2.14.7
npm info using node@v4.2.1
```
Environments where this is reproduced: 
1. Windows 8, using cygwin inside of ConEmu
2. Linux (not sure which distro)

Getting error
```
events.js:141
      throw er; // Unhandled 'error' event
      ^
TypeError: this is not a typed array.
    at Function.from (native)
    at DestroyableTransform._transform (...\node_modules\gulp-strip-css-comments\index.js:18:27)
```

Looks like `Buffer.from` works only since Node v6?
https://github.com/sindresorhus/gulp-strip-css-comments/commit/cf396777970274c2f1f377a7cdd524171cd29199#diff-168726dbe96b3ce427e7fedce31bb0bcR18

https://stackoverflow.com/a/36924697

With node v8.9.3 the same gulp task works fine.

**Comment by sindresorhus** [comment]
You're on an outdated Node.js 4 version. Just upgrade to the latest Node.js 4 version.

**Comment by DarthVanger** [comment]
Thanks, mb will try that some day :) For now just switched to using previous version of your lib :)
Anyways, probably would make sense to specify the needed version in the `engines` field of `package.json`, e.g. `>= 4.8.7` or whatever version is needed to make this lib work.

**Comment by sindresorhus** [comment]
It's expected that users upgrade Node.js patch versions.
