### ISSUE TITLE
whitespace: false doesn't seem to be working for me

### ISSUE THREAD

**Issue by EmSixTeen** [sindresorhus/gulp-strip-css-comments#6]
When I add the `whitespace: false` option to stripCssComments it doesn't seem to have any effect - Am I doing something wrong, or is this a bug?

**Dependencies:**
autoprefixer: 10.4.13
gulp: 4.0.2
gulp-postcss: 9.0.1
gulp-sass: 5.1.0
gulp-strip-css-comments: 2.0.0
sass: 1.56.1

**Gulp file:**
```js
const gulp = require('gulp');
const sass = require('gulp-sass')(require('sass'));
const stripCssComments = require('gulp-strip-css-comments');
const autoprefixer = require('autoprefixer');
const postcss = require('gulp-postcss');

gulp.task('sass', () => {
  return (
    gulp
      .src('./src/sass/*.scss')

      .pipe(postcss([autoprefixer()]))
      .pipe(sass({ errLogToConsole: true, outputStyle: 'expanded' })) 
      .pipe(stripCssComments({ whitespace: false }))
      .pipe(gulp.dest('./public/css'))
  );
});
```

**Comment by sindresorhus** [comment]
I have a test that proves it's working now at least: https://github.com/sindresorhus/gulp-strip-css-comments/blob/c60d9200370064710e44158edf89113d612f32fd/test.js#L19-L29
